services:
  echo:
    image: kftlfd/c-http-server:1.0
    build: .
    ports:
      - 8888:8000

  static:
    image: kftlfd/c-http-server:1.0
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./public:/app/html
    command: [ "server", "fs", "/app/html", "--host=0.0.0.0", "--port=8000" ]
